apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gmp-test
  labels:
    app.kubernetes.io/name: prometheus-example-app
  name: prometheus-example-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app

  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-example-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
      - image: ikaushik96/mynodeapp:latest
        name: prom-example
        ports:
        - name: metrics
          containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  namespace: gmp-test
spec:
  selector:
    app.kubernetes.io/name: prometheus-example-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: metrics
  type: LoadBalancer
